// Code generated by protoc-gen-cc-gateway. DO NOT EDIT.
// source: commercial-paper.proto

/*
Package proto contains
  *   chaincode interface definition
  *   chaincode gateway definition
  *   chaincode service to cckit router registration func
*/
package proto

import (
	context "context"

	"github.com/golang/protobuf/ptypes/empty"
	errors "github.com/pkg/errors"
	cckit_gateway "github.com/s7techlab/cckit/gateway"
	cckit_ccservice "github.com/s7techlab/cckit/gateway/service"
	cckit_router "github.com/s7techlab/cckit/router"
	cckit_param "github.com/s7techlab/cckit/router/param"
	cckit_defparam "github.com/s7techlab/cckit/router/param/defparam"
)

type ValidatorInterface interface {
	Validate() error
}

// CPaperChaincode  method names
const (
	CPaperChaincode_List = "List"

	CPaperChaincode_Get = "Get"

	CPaperChaincode_GetByExternalId = "GetByExternalId"

	CPaperChaincode_Issue = "Issue"

	CPaperChaincode_Buy = "Buy"

	CPaperChaincode_Redeem = "Redeem"

	CPaperChaincode_Delete = "Delete"
)

// CPaperChaincode chaincode methods interface
type CPaperChaincode interface {
	List(cckit_router.Context, *empty.Empty) (*CommercialPaperList, error)

	Get(cckit_router.Context, *CommercialPaperId) (*CommercialPaper, error)

	GetByExternalId(cckit_router.Context, *ExternalId) (*CommercialPaper, error)

	Issue(cckit_router.Context, *IssueCommercialPaper) (*CommercialPaper, error)

	Buy(cckit_router.Context, *BuyCommercialPaper) (*CommercialPaper, error)

	Redeem(cckit_router.Context, *RedeemCommercialPaper) (*CommercialPaper, error)

	Delete(cckit_router.Context, *CommercialPaperId) (*CommercialPaper, error)
}

// RegisterCPaperChaincode registers service methods as chaincode router handlers
func RegisterCPaperChaincode(r *cckit_router.Group, cc CPaperChaincode) error {

	r.Query(CPaperChaincode_List,
		func(ctx cckit_router.Context) (interface{}, error) {
			if v, ok := ctx.Param().(ValidatorInterface); ok {
				if err := v.Validate(); err != nil {
					return nil, errors.Wrap(err, cckit_param.ErrPayloadValidationError.Error())
				}
			}
			return cc.List(ctx, ctx.Param().(*empty.Empty))
		},
		cckit_defparam.Proto(&empty.Empty{}))

	r.Query(CPaperChaincode_Get,
		func(ctx cckit_router.Context) (interface{}, error) {
			if v, ok := ctx.Param().(ValidatorInterface); ok {
				if err := v.Validate(); err != nil {
					return nil, errors.Wrap(err, cckit_param.ErrPayloadValidationError.Error())
				}
			}
			return cc.Get(ctx, ctx.Param().(*CommercialPaperId))
		},
		cckit_defparam.Proto(&CommercialPaperId{}))

	r.Query(CPaperChaincode_GetByExternalId,
		func(ctx cckit_router.Context) (interface{}, error) {
			if v, ok := ctx.Param().(ValidatorInterface); ok {
				if err := v.Validate(); err != nil {
					return nil, errors.Wrap(err, cckit_param.ErrPayloadValidationError.Error())
				}
			}
			return cc.GetByExternalId(ctx, ctx.Param().(*ExternalId))
		},
		cckit_defparam.Proto(&ExternalId{}))

	r.Invoke(CPaperChaincode_Issue,
		func(ctx cckit_router.Context) (interface{}, error) {
			if v, ok := ctx.Param().(ValidatorInterface); ok {
				if err := v.Validate(); err != nil {
					return nil, errors.Wrap(err, cckit_param.ErrPayloadValidationError.Error())
				}
			}
			return cc.Issue(ctx, ctx.Param().(*IssueCommercialPaper))
		},
		cckit_defparam.Proto(&IssueCommercialPaper{}))

	r.Invoke(CPaperChaincode_Buy,
		func(ctx cckit_router.Context) (interface{}, error) {
			if v, ok := ctx.Param().(ValidatorInterface); ok {
				if err := v.Validate(); err != nil {
					return nil, errors.Wrap(err, cckit_param.ErrPayloadValidationError.Error())
				}
			}
			return cc.Buy(ctx, ctx.Param().(*BuyCommercialPaper))
		},
		cckit_defparam.Proto(&BuyCommercialPaper{}))

	r.Invoke(CPaperChaincode_Redeem,
		func(ctx cckit_router.Context) (interface{}, error) {
			if v, ok := ctx.Param().(ValidatorInterface); ok {
				if err := v.Validate(); err != nil {
					return nil, errors.Wrap(err, cckit_param.ErrPayloadValidationError.Error())
				}
			}
			return cc.Redeem(ctx, ctx.Param().(*RedeemCommercialPaper))
		},
		cckit_defparam.Proto(&RedeemCommercialPaper{}))

	r.Invoke(CPaperChaincode_Delete,
		func(ctx cckit_router.Context) (interface{}, error) {
			if v, ok := ctx.Param().(ValidatorInterface); ok {
				if err := v.Validate(); err != nil {
					return nil, errors.Wrap(err, cckit_param.ErrPayloadValidationError.Error())
				}
			}
			return cc.Delete(ctx, ctx.Param().(*CommercialPaperId))
		},
		cckit_defparam.Proto(&CommercialPaperId{}))

	return nil
}

// NewCPaperGateway creates gateway to access chaincode method via chaincode service
func NewCPaperGateway(ccService cckit_ccservice.Chaincode, channel, chaincode string, opts ...cckit_gateway.Opt) *CPaperGateway {
	return &CPaperGateway{Gateway: cckit_gateway.NewChaincode(ccService, channel, chaincode, opts...)}
}

// gateway implementation
// gateway can be used as kind of SDK, GRPC or REST server ( via grpc-gateway or clay )
type CPaperGateway struct {
	Gateway cckit_gateway.Chaincode
}

// ApiDef returns service definition
func (c *CPaperGateway) ApiDef() cckit_gateway.ServiceDef {
	return cckit_gateway.ServiceDef{
		Desc:                        &_CPaper_serviceDesc,
		Service:                     c,
		HandlerFromEndpointRegister: RegisterCPaperHandlerFromEndpoint,
	}
}

// Events returns events subscription
func (c *CPaperGateway) Events(ctx context.Context) (cckit_gateway.ChaincodeEventSub, error) {
	return c.Gateway.Events(ctx)
}

func (c *CPaperGateway) List(ctx context.Context, in *empty.Empty) (*CommercialPaperList, error) {
	var inMsg interface{} = in
	if v, ok := inMsg.(ValidatorInterface); ok {
		if err := v.Validate(); err != nil {
			return nil, err
		}
	}

	if res, err := c.Gateway.Query(ctx, CPaperChaincode_List, []interface{}{in}, &CommercialPaperList{}); err != nil {
		return nil, err
	} else {
		return res.(*CommercialPaperList), nil
	}
}

func (c *CPaperGateway) Get(ctx context.Context, in *CommercialPaperId) (*CommercialPaper, error) {
	var inMsg interface{} = in
	if v, ok := inMsg.(ValidatorInterface); ok {
		if err := v.Validate(); err != nil {
			return nil, err
		}
	}

	if res, err := c.Gateway.Query(ctx, CPaperChaincode_Get, []interface{}{in}, &CommercialPaper{}); err != nil {
		return nil, err
	} else {
		return res.(*CommercialPaper), nil
	}
}

func (c *CPaperGateway) GetByExternalId(ctx context.Context, in *ExternalId) (*CommercialPaper, error) {
	var inMsg interface{} = in
	if v, ok := inMsg.(ValidatorInterface); ok {
		if err := v.Validate(); err != nil {
			return nil, err
		}
	}

	if res, err := c.Gateway.Query(ctx, CPaperChaincode_GetByExternalId, []interface{}{in}, &CommercialPaper{}); err != nil {
		return nil, err
	} else {
		return res.(*CommercialPaper), nil
	}
}

func (c *CPaperGateway) Issue(ctx context.Context, in *IssueCommercialPaper) (*CommercialPaper, error) {
	var inMsg interface{} = in
	if v, ok := inMsg.(ValidatorInterface); ok {
		if err := v.Validate(); err != nil {
			return nil, err
		}
	}

	if res, err := c.Gateway.Invoke(ctx, CPaperChaincode_Issue, []interface{}{in}, &CommercialPaper{}); err != nil {
		return nil, err
	} else {
		return res.(*CommercialPaper), nil
	}
}

func (c *CPaperGateway) Buy(ctx context.Context, in *BuyCommercialPaper) (*CommercialPaper, error) {
	var inMsg interface{} = in
	if v, ok := inMsg.(ValidatorInterface); ok {
		if err := v.Validate(); err != nil {
			return nil, err
		}
	}

	if res, err := c.Gateway.Invoke(ctx, CPaperChaincode_Buy, []interface{}{in}, &CommercialPaper{}); err != nil {
		return nil, err
	} else {
		return res.(*CommercialPaper), nil
	}
}

func (c *CPaperGateway) Redeem(ctx context.Context, in *RedeemCommercialPaper) (*CommercialPaper, error) {
	var inMsg interface{} = in
	if v, ok := inMsg.(ValidatorInterface); ok {
		if err := v.Validate(); err != nil {
			return nil, err
		}
	}

	if res, err := c.Gateway.Invoke(ctx, CPaperChaincode_Redeem, []interface{}{in}, &CommercialPaper{}); err != nil {
		return nil, err
	} else {
		return res.(*CommercialPaper), nil
	}
}

func (c *CPaperGateway) Delete(ctx context.Context, in *CommercialPaperId) (*CommercialPaper, error) {
	var inMsg interface{} = in
	if v, ok := inMsg.(ValidatorInterface); ok {
		if err := v.Validate(); err != nil {
			return nil, err
		}
	}

	if res, err := c.Gateway.Invoke(ctx, CPaperChaincode_Delete, []interface{}{in}, &CommercialPaper{}); err != nil {
		return nil, err
	} else {
		return res.(*CommercialPaper), nil
	}
}
